spring:
  application:
    name: bq-config-service

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pearpai/spring-cloud
         

